### PR TITLE
Start testing on windows

### PR DESCRIPTION
**Pull request by voxpelli**
Currently these tests are failing on Windows. They shouldn't be.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@voxpelli If you switch to double quotes around the globs, does it fix these tests?

**Comment by voxpelli** [comment]
Seems like that unfortunately didn't do the trick @blakeembrey 🤔

**Comment by armano2** [comment]
one of issues is 
https://github.com/dependency-check-team/dependency-check/blob/0cb6065a760905976c6a4cf4b752cfa6b9b9d35d/index.js#L52-L54

you should use `path.sep` as separator

**Comment by achingbrain** [comment]
This just bit me so I've opened #127 which passes the tests for me on Windows.  Looks like GH actions aren't running on PR branches though it's run on the branch in my fork here and Windows is green: https://github.com/achingbrain/dependency-check/actions/runs/362021862

**Comment by voxpelli** [comment]
Fixed by #127 🎉

**Pull request closed without merging**
